language: android
jdk: oraclejdk17

android:
  components:
    - tools
    - platform-tools
    - tools # Running this twice gets the latest build tools
    - build-tools-30.0.3
    - android-30
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean build

branches:
  only:
    - master
    - main

notifications:
  email: false
